name: Build Function

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install
        run: |
          cd functions
          yarn install
      - name: Lint
        run: |
          cd functions
          yarn lint
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: nike-stock-scraper
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Register Service Account
        run: |
          cd functions
          touch sa.json
          echo '${{ secrets.SERVICE_ACCOUNT }}' > sa.json
      - name: Build
        run: |
          sudo npm install -g firebase-tools
      - name: Deploy
        run: |
          firebase deploy --only functions:prod --token ${{ secrets.FIREBASE_TOKEN }}
