name: Build Function

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install
        run: |
          yarn install
      - name: Lint
        run: |
          yarn lint
      - name: Register Service Account
        run: |
          touch sa.json
          echo '${{ secrets.SERVICE_ACCOUNT }}' >> sa.json
      - name: Deploy
        run: |
          gcloud functions deploy nike-stock-scraper
