name: Build Function

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install
        run: |
          yarn install
      - name: Lint
        run: |
          yarn lint
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: nike-stock-scraper
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Register Service Account
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT }}' > sa.json
      - name: Auth with gcloud
        run: |
          gcloud auth activate-service-account --key-file=sa.json
      - name: Deploy
        run: |
          gcloud functions deploy nike-stock-scraper --source lib --runtime nodejs18 --trigger-http --allow-unauthenticated
